### ISSUE TITLE
Pricedrop check

### ISSUE THREAD

**Issue by iSpid3r** [xMrVizzy/Shortcuts#13]
Add pricedrop check, please. At least manual like in this shortcut: https://www.icloud.com/shortcuts/57f49ec6076c47238ebd93aaacd9fef3

**Comment by xMrVizzy** [comment]
Done in new update!

**Comment by iSpid3r** [comment]
Pricedrop button doing nothing.

**Comment by xMrVizzy** [comment]
Price Drop button will open if at least one app has price Drop

**Comment by xMrVizzy** [comment]
Price Drop button will open if at least one app has price Drop
