### ISSUE TITLE
Adds modifications

### ISSUE THREAD

**Issue by Machou** [xMrVizzy/Shortcuts#42]
Hi

In the **Toolbox**, can you change the **other.emoji**, Add **Available Emoji** if _Emoji = 1_, or **Availables Emojis** if _Emoji > 1_

In the **ShareShortHub**, it's possible to translate all Categories ? (API, Calculcations, Fun, Homekit, Messaging, Music...etc)

**Comment by xMrVizzy** [comment]
Oh yeah awesome! I will implement Categories for now!!!
